name: Build tg-up

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags (e.g., v1.0.0)
    branches:
      - main
    paths:
      - 'go.mod'
      - 'main.go'
      - 'build.sh'
      - 'go.sum'
      - 'VERSION.txt'
    
  workflow_dispatch:

jobs:
  build_and_release:
    name: Build (${{ matrix.goos }}-${{ matrix.goarch }})
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows # Exclude windows/arm64
            goarch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' 

      - name: Read Version from File
        id: version_file
        run: echo "app_version=$(cat VERSION.txt | tr -d ' \t\n\r')" >> $GITHUB_OUTPUT
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git upx-ucl

      - name: Make scripts executable
        run: chmod +x build.sh upx.sh

      - name: Build and Compress tg-up
      # Pass GOOS, GOARCH, and the version read from the file to the build script
        run: |
          ./build.sh ${{ matrix.goos }} ${{ matrix.goarch }} ${{ steps.version_file.outputs.app_version }}
          ./upx.sh

      - name: Create or Update GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }} (App Version: ${{ steps.version_file.outputs.app_version }})
            
            Multi-platform binaries attached below.
          draft: true # Change to 'false' to publish immediately
        env:
          GITHUB_TOKEN: ${{ github.token }}